### PR TITLE
bumped node version to v16

### PR DESCRIPTION
**Pull request by varxnnn**

### CODE REVIEW

**Comment by gerred** [comment]
@varxnnn is this something you still wanted merged? Happy to merge it.

**Comment by varxnnn** [comment]
Yeah I mean, node 12 runners are getting discontinued soon and I'm using your action in my workflow. So it'd be nice if we could bump node to v16.

**Comment by varxnnn** [comment]
@gerred

**Comment by gerred** [comment]
@varxnnn done! I usually only check GH notifications once a day, so happy to get this updated.

**Comment by varxnnn** [comment]
@gerred thanks a ton! have a great day.

**Pull request merged**
